#!/usr/bin/env bash
#
# Demonstration script for leaf.sh
# Record this with: asciinema rec leaf-demo.cast -c "bash leaf-demo.sh"
#

# Colors for better visibility
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Function to print and execute commands with delay
demo() {
    echo -e "${BLUE}$ ${NC}$1"
    sleep 1
    eval "$1"
    sleep 2
}

# Function to print commentary
comment() {
    echo -e "${YELLOW}# $1${NC}"
    sleep 2
}

clear

echo -e "${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                       ║${NC}"
echo -e "${GREEN}║    🍃 butter.sh Ecosystem - leaf.sh Demo              ║${NC}"
echo -e "${GREEN}║    Documentation Generator                            ║${NC}"
echo -e "${GREEN}║                                                       ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}"
echo ""
sleep 3

comment "Install leaf.sh - the documentation generator"
demo "git clone https://github.com/butter-sh/leaf.sh.git"
demo "cd leaf.sh && sudo make install"

comment "Create a sample project to document"
mkdir -p ~/sample-project && cd ~/sample-project

cat > README.md << 'EOF'
# Sample Project

This is a sample bash project to demonstrate leaf.sh documentation generation.

## Features

- Feature 1: Does something awesome
- Feature 2: Does something else
- Feature 3: Makes everything better

## Installation

```bash
git clone https://github.com/user/sample-project.git
cd sample-project
./install.sh
```

## Usage

```bash
./sample-project.sh --help
```

## Contributing

Contributions welcome! Please submit a PR.
EOF

cat > sample-project.sh << 'EOF'
#!/usr/bin/env bash
#
# Sample Project - A demonstration bash script
# Version: 1.0.0
# Author: butter.sh team
#

# Main function
main() {
    echo "🧈 Welcome to Sample Project!"
    echo "This is generated by butter.sh ecosystem"
}

# Help function
show_help() {
    cat << 'HELP'
Usage: sample-project.sh [OPTIONS]

Options:
    -h, --help      Show this help message
    -v, --version   Show version information
    -c, --config    Specify config file

Examples:
    ./sample-project.sh --help
    ./sample-project.sh --config config.yml
HELP
}

# Parse arguments
case "${1:-}" in
    -h|--help)
        show_help
        ;;
    -v|--version)
        echo "Version 1.0.0"
        ;;
    *)
        main
        ;;
esac
EOF

chmod +x sample-project.sh

cat > LICENSE << 'EOF'
MIT License

Copyright (c) 2025 butter.sh team

Permission is hereby granted, free of charge...
EOF

cat > arty.yml << 'EOF'
name: "sample-project"
version: "1.0.0"
description: "A sample bash project for documentation"
author: "butter.sh team"
license: "MIT"

main: "sample-project.sh"

scripts:
  test: "bash tests/run.sh"
  start: "bash sample-project.sh"
EOF

demo "ls -la"

comment "Generate documentation with leaf.sh"
demo "leaf.sh ."

comment "View the generated documentation structure"
demo "tree docs -L 2"

comment "Check the generated HTML files"
demo "ls -la docs/"

comment "View the index.html content (first 30 lines)"
demo "head -n 30 docs/index.html"

comment "The documentation includes:"
echo "  ✨ Responsive design with Tailwind CSS"
echo "  🎨 Syntax highlighting for code blocks"
echo "  🌓 Dark/light theme support"
echo "  📱 Mobile-friendly layout"
echo "  🚀 Auto-parsed README, LICENSE, and source files"
sleep 3

comment "You can now open the docs in a browser:"
echo "  open docs/index.html"
sleep 2

comment "Or serve them with a simple HTTP server:"
demo "cd docs && python3 -m http.server 8080 &"
sleep 2
echo "  📡 Documentation served at http://localhost:8080"
sleep 2
demo "pkill -f 'python3 -m http.server'"

comment "leaf.sh automatically parses:"
echo "  📄 README.md → Landing page"
echo "  📜 LICENSE → License page"
echo "  💻 *.sh files → Source code pages with syntax highlighting"
echo "  📋 arty.yml → Project configuration"
sleep 3

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                       ║${NC}"
echo -e "${GREEN}║    ✨ leaf.sh Demo Complete!                          ║${NC}"
echo -e "${GREEN}║    Learn more: https://butter-sh.github.io/leaf.sh    ║${NC}"
echo -e "${GREEN}║                                                       ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════╝${NC}"
echo ""
sleep 3
